<a href="https://colab.research.google.com/github/mvharsh/Deep-Learning/blob/main/ANN/ANN_Iris_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Load the Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
# Splitting the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Building the ANN model
model = Sequential()
model.add(Dense(8, activation='relu', input_dim=X_train_scaled.shape[1]))
model.add(Dense(3, activation='softmax'))

In [ ]:
# Compiling the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [ ]:
# Training the model
model.fit(X_train_scaled, y_train, epochs=100, batch_size=10, validation_split=0.1)

Epoch 1/100
11/11 [==============================] - 4s 86ms/step - loss: 1.1795 - accuracy: 0.4722 - val_loss: 1.2184 - val_accuracy: 0.4167
Epoch 2/100
11/11 [==============================] - 0s 34ms/step - loss: 1.1053 - accuracy: 0.6481 - val_loss: 1.1775 - val_accuracy: 0.5833
Epoch 3/100
11/11 [==============================] - 0s 19ms/step - loss: 1.0395 - accuracy: 0.6759 - val_loss: 1.1375 - val_accuracy: 0.5833
Epoch 4/100
11/11 [==============================] - 0s 19ms/step - loss: 0.9828 - accuracy: 0.6759 - val_loss: 1.0982 - val_accuracy: 0.5833
Epoch 5/100
11/11 [==============================] - 0s 30ms/step - loss: 0.9314 - accuracy: 0.6759 - val_loss: 1.0611 - val_accuracy: 0.5833
Epoch 6/100
11/11 [==============================] - 0s 12ms/step - loss: 0.8863 - accuracy: 0.6759 - val_loss: 1.0289 - val_accuracy: 0.5833
Epoch 7/100
11/11 [==============================] - 0s 12ms/step - loss: 0.8462 - accuracy: 0.6852 - val_loss: 0.9986 - val_accuracy: 0.5833
Epoch 

In [ ]:
# Evaluating the model
y_pred = np.argmax(model.predict(X_test_scaled), axis=-1)

1/1 [==============================] - 0s 244ms/step


In [ ]:
# Calculate evaluation metrics
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average='macro')
recall = recall_score(y_test, y_pred, average='macro')
f1 = f1_score(y_test, y_pred, average='macro')
conf_matrix = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(conf_matrix)
print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1 Score:", f1)

Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Accuracy: 0.9666666666666667
Precision: 0.9722222222222222
Recall: 0.9629629629629629
F1 Score: 0.9658994032395567


In [ ]:
feature_names = iris.feature_names
user_input = []
for feature in feature_names:
    value = float(input(f"Enter {feature}: "))
    user_input.append(value)

# Scale the user input
user_input_scaled = scaler.transform([user_input])

# Predict the outcome
predicted_class = np.argmax(model.predict(user_input_scaled), axis=-1)
class_names = iris.target_names
print(f"Predicted class: {class_names[predicted_class[0]]}")

Enter sepal length (cm): 4.4
Enter sepal width (cm): 3.2
Enter petal length (cm): 4
Enter petal width (cm): 1
1/1 [==============================] - 0s 22ms/step
Predicted class: setosa
